# Canonical skill names + common aliases. Used by the normalizer and the
# unstructured-text extractor to collapse "JS"/"Javascript"/"node.js" etc.
SKILL_ALIASES = {
    "js": "JavaScript", "javascript": "JavaScript", "ecmascript": "JavaScript",
    "ts": "TypeScript", "typescript": "TypeScript",
    "py": "Python", "python": "Python", "python3": "Python",
    "node": "Node.js", "nodejs": "Node.js", "node.js": "Node.js",
    "react": "React", "reactjs": "React", "react.js": "React",
    "next": "Next.js", "nextjs": "Next.js", "next.js": "Next.js",
    "vue": "Vue.js", "vuejs": "Vue.js",
    "ng": "Angular", "angular": "Angular",
    "express": "Express.js", "expressjs": "Express.js",
    "fastapi": "FastAPI", "flask": "Flask", "django": "Django",
    "springboot": "Spring Boot", "spring boot": "Spring Boot",
    "firebase": "Firebase", "room": "Room Database", "room database": "Room Database",
    "gradle": "Gradle", "maven": "Maven", "postman": "Postman", "vercel": "Vercel",
    "keras": "Keras", "sentence-bert": "Sentence-BERT", "sbert": "Sentence-BERT",
    "tf": "TensorFlow", "tensorflow": "TensorFlow",
    "pytorch": "PyTorch", "torch": "PyTorch",
    "sklearn": "scikit-learn", "scikit-learn": "scikit-learn",
    "numpy": "NumPy", "np": "NumPy",
    "pandas": "pandas", "pd": "pandas",
    "sql": "SQL", "mysql": "MySQL", "postgres": "PostgreSQL", "postgresql": "PostgreSQL",
    "mongo": "MongoDB", "mongodb": "MongoDB", "redis": "Redis",
    "aws": "AWS", "gcp": "GCP", "azure": "Azure",
    "docker": "Docker", "k8s": "Kubernetes", "kubernetes": "Kubernetes",
    "git": "Git", "github": "GitHub", "gitlab": "GitLab",
    "linux": "Linux", "bash": "Bash", "shell": "Shell",
    "html": "HTML", "css": "CSS", "tailwind": "Tailwind CSS",
    "rest": "REST APIs", "graphql": "GraphQL",
    "java": "Java", "c++": "C++", "cpp": "C++", "c#": "C#", "go": "Go", "golang": "Go",
    "rust": "Rust", "ruby": "Ruby", "php": "PHP", "kotlin": "Kotlin", "swift": "Swift",
    "ml": "Machine Learning", "machine learning": "Machine Learning",
    "nlp": "NLP", "llm": "LLMs", "llms": "LLMs",
}
